controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_controller:
      type: joint_state_controller/JointStateController

effort_controllers:
  ros__parameters:
    joints:
      - slider_to_cart
<<<<<<< HEAD
    interface_name: position  # does an effort controller still interface off position?
=======
>>>>>>> eb2235b1ff9db1ca129e4b6866096e3b27f91193
