controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_based_velocity_controller:
      type: effort_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_based_velocity_controller:
  ros__parameters:
    joints:
      - slider_to_cart
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      slider_to_cart:
        p: 1.0
        i: 1.0
        d: 1.0
    joint_limits:
      slider_to_cart:
        has_position_limits: true
        has_velocity_limits: true
        has_acceleration_limits: false
        has_effort_limits: true
        has_jerk_limits: false
        angle_wraparound: true
        min_position: -10.0
        max_position: 10.0
        max_velocity: 2.0
        max_acceleration: 1.0
        max_jerk: 1.0
        max_effort: 900.0
        # has_soft_limits:   # currently unsupported
        # k_position:   # currently unsupported
        # k_velocity:   # currently unsupported
        # soft_lower_limit:   # currently unsupported 
        # soft_upper_limit:   # currently unsupported
