controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_based_position_controller:
      type: effort_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_state_publisher:
  ros__parameters:
    joints:
      - slider_to_cart
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      - slider_to_cart:
        - p: 10.0
        - i: 1.0
        - d: 10.0
#    limits:
#      - slider_to_cart:
#        - has_position_limits: 1
#        - has_velocity_limits: 0
#        - has_acceleration_limits: 0
#        - has_effort_limits: 1 
#        - has_jerk_limits: 0
#        - angle_wraparound: 1
#        - min_position: -10
#        - max_position: 10
#        - max_velocity: 2
#        - max_acceleration: 1
#        - max_jerk: 1
#        - max_effort: 900
#        - has_soft_limits:   # currently unsupported
#        - k_position:   # currently unsupported
#        - k_velocity:   # currently unsupported
#        - soft_lower_limit:   # currently unsupported 
#        - soft_upper_limit:   # currently unsupported
